// <auto-generated />
namespace SoyalWorkTimeWebManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nogroupreq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nogroupreq));
        
        string IMigrationMetadata.Id
        {
            get { return "201404071431027_nogroupreq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
